name: adcal-20-18
on:
  schedule:
    # 12/18 の 0:00 (JST) に処理を実行する。(UTC の 15:00 は JST だと翌日の 0:00)
    - cron: "0 15 17 12 *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: merge adcal branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name hrsma2i
          git config user.email hrs.ma2i@gmail.com
          git merge -m "Merge branch adcal-20-18" origin/adcal-20-18
      - name: push default branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
